source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Facelytics_Example', :exclusive => true do
  pod "Facelytics", :path => "../"
end

target 'Facelytics_Tests', :exclusive => true do
  pod "Facelytics", :path => "../"

  
end
